### ISSUE TITLE
AWS Amplify Build - Cannot Find graphql-ttl-transformer 

### ISSUE THREAD

**Issue by LoukasGP** [flogy/graphql-ttl-transformer#19]
Hello,

1. I have read this article offering a [build solution](https://github.com/flogy/graphql-ttl-transformer/issues/3).
2. I have added this to my transform.conf.json file `"transformers": ["graphql-ttl-transformer"]`
3. I have installed this package on my project `"graphql-ttl-transformer": "^2.0.0"`,
4. The localhost ttl fields via graphql schema work and show in DynamoDB
5. I am using Next.js and AWS Amplify
6. I am using `"transformerversion": 2` in the `cli.json` file.

**Error:**
🛑 Unable to import custom transformer module(graphql-ttl-transformer).
🛑 You may fix this error by editing transformers at graphql-ttl-transformer/transform.conf.json
✖ An error occurred when pushing the resources to the cloud
✖ There was an error initializing your environment.
Cannot find module '/root/.amplify/lib/node_modules/graphql-ttl-transformer'

**Build File for AWS Amplify Hosting:**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install 
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
